name: "My Workbook"
description : "This website contains my notes"
baseurl : ""

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:title.html
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

